[package]
categories = ["multimedia::images"]
description = "Convert 24/32-bit images to 8-bit palette with alpha channel. Bindings for libimagequant that powers pngquant lossy PNG compressor."
documentation = "https://pngquant.org/lib/"
include = ["src/*", "examples/*", "COPYRIGHT", "Cargo.toml", "README.md"]
keywords = ["quantization", "palette", "image", "pngquant", "compression"]
authors = [ "Kornel <kornel@pngquant.org>" ]
license = "GPL-3.0+"
name = "imagequant"
repository = "https://github.com/pornel/libimagequant-rust.git"
version = "2.11.0"

[dependencies]
imagequant-sys = "0.1.0"

[features]
default = ["sse"]
sse = ["imagequant-sys/sse"]

[lib]
name = "imagequant"
