[package]
categories = ["multimedia::images"]
description = "Convert 24/32-bit images to 8-bit palette with alpha channel.\nBindings for libimagequant that powers pngquant lossy PNG compressor.\n\nDual-licensed like pngquant. See https://pngquant.org for details."
documentation = "https://docs.rs/imagequant"
homepage = "https://pngquant.org/lib/"
include = ["src/*", "examples/*", "COPYRIGHT", "Cargo.toml", "README.md"]
keywords = ["quantization", "palette", "image", "pngquant", "compression"]
authors = [ "Kornel <kornel@pngquant.org>" ]
license = "GPL-3.0+"
name = "imagequant"
readme = "README.md"
repository = "https://github.com/pornel/libimagequant-rust.git"
version = "2.11.3"

[dependencies]
imagequant-sys = "2.10.0"

[features]
default = ["sse"]
sse = ["imagequant-sys/sse"]

[lib]
name = "imagequant"
