[package]
name = "imagequant"
version = "4.0.0-beta.1"
description = "Convert 24/32-bit images to 8-bit palette with alpha channel.\nBindings for libimagequant that powers pngquant lossy PNG compressor.\n\nDual-licensed like pngquant. See https://pngquant.org for details."
authors = ["Kornel Lesiński <kornel@pngquant.org>"]
license = "GPL-3.0-or-later"
homepage = "https://pngquant.org/lib"
repository = "https://github.com/ImageOptim/libimagequant"
documentation = "https://docs.rs/imagequant"
categories = ["multimedia::images"]
keywords = ["quantization", "palette", "image", "pngquant", "compression"]
include = ["COPYRIGHT", "src/*.rs", "*.h", "README.md", "Cargo.toml"]
readme = "README.md"
edition = "2018"

[lib]
crate-type = ["cdylib", "staticlib", "lib"]
doctest = false

[dependencies]
arrayvec = "0.7.2"
bitflags = "1.3.2"
fallible_collections = "0.4.3"
libc = "0.2.109"
noisy_float = "0.2.0"
rayon = "1.5.1"
rgb = { version = "0.8.30", features = ["argb"] }
thread_local = "1.1.3"

[dev-dependencies]
lodepng = "3.4.7"
